analyzer:
    errors:
      use_build_context_synchronously: ignore
      library_private_types_in_public_api: ignore
include: package:flutter_lints/flutter.yaml

linter:
    rules:
        file_names: false
        non_constant_identifier_names: false
