name: unilodge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dlibphonenumber: ^1.1.22
  flutter:
    sdk: flutter
  flutter_svg:
  go_router: ^14.2.3
  google_nav_bar: ^5.0.6
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  get: ^4.6.5
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/initLogo1.png
    - assets/images/initLogo2.png
    - assets/images/empty.png
    - assets/images/apartment.png
    - assets/images/dorm.png
    - assets/images/solo-room.png
    - assets/images/bedspacer.png
    - assets/images/emptyImage.jpg
    - assets/images/findDorm.png
    - assets/images/google_logo.png

  fonts:
    - family: TrainOne
      fonts:
        - asset: assets/fonts/TrainOne-Regular.ttf
          weight: 400
